# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Private CI trigger.  Used to run tooling that can't currently be shared
# publicly.

trigger: none
pr: none

# The runner used for private CI enforces the use of the template below. All
# build steps need to be placed into the template.
resources:
  repositories:
  - repository: lowrisc-private-ci
    type: github
    endpoint: lowRISC
    name: lowrisc/lowrisc-private-ci
    ref: refs/heads/spike_build_test

extends:
  template: spike-build.yml@lowrisc-private-ci
